# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: health_development

test:
  <<: *default
  database: health_test

production:
  primary: &primary_production
    <<: *default
    database: health_production
  cache:
    <<: *primary_production
    database: health_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: health_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: health_production_cable
    migrations_paths: db/cable_migrate
